### PR TITLE
Move the syntax highlighter to Prism

### PR DESCRIPTION
**Pull request by bpierre**

### CODE REVIEW

**Comment by bpierre** [comment]
We need to change every post, to replace `<pre class="brush:css">` with `<pre class="language-css"><code>`.

**Comment by bpierre** [comment]
The correct syntax is:

``` html
<pre><code class="language-css">
<pre><code class="language-html">
<pre><code class="language-javascript">
```

**Comment by ericlebihan** [comment]
is it already working yet ?

**Comment by bpierre** [comment]
Since 3 minutes :-)

**Comment by ericlebihan** [comment]
cool :-)

**Comment by ericlebihan** [comment]
What about .styl, .less and .sass ?

**Comment by bpierre** [comment]
That is an excellent question :-)

**Comment by ericlebihan** [comment]
Is it possible to change the colors ? It's not very readable with the brown
background in the current version of lesintegristes

**Comment by bpierre** [comment]
I took the colors selected by Grégoire for the previous script
(SyntaxHighlighter). But the classification of labels has changed, and the
green color, for example, is too much present. We need a new and more
complete (7-8 colors) color scheme, @gregoiredierendonck is working on it.

**Comment by bpierre** [comment]
OK sorry again, the definitive syntax is:

``` html
<pre><code class="language-css"> <!-- CSS -->
<pre><code class="language-markup"> <!-- HTML, XML -->
<pre><code class="language-javascript"> <!-- JavaScript -->
```

**Pull request merged**
