### PR TITLE
Remove IE6, IE7 and IE8 support

### PR DESCRIPTION
**Pull request by bpierre**

### CODE REVIEW

**Comment by bpierre** [comment]
Future, here we are!

**Comment by bpierre** [comment]
The website is now broken with dinosaurs: IE6, IE7, IE8.

Some stats for the last 30 days:

stats

**Comment by ericlebihan** [comment]
Hum... I can't find those browsers on my iMac...

**Comment by bpierre** [comment]
Me neither, the Web moves too fast :-)

Last week:

last week stats

**Comment by grid23** [comment]
The update system of Firefox seems to work not too badly after all. :-)

**Pull request merged**
